- name: Deploy Azure Red Hat OpenShift 4.x
  hosts: localhost
  connection: local

  roles:
    - ./modules

  vars:
      azure_dc: "eastus"
      client_id: "8f5f15d4-0812-40e5-ae4e-c9accd0770fa"
      client_secret: "o8S6-lN5SJX.UvJ_ENtjv6W_nex8lJsZUf"
      cluster_name: "aro4-ansible"
      resource_group: "aro4-ansible"
      aro_vnet: "AROVNet"
      aro_master_subnet: "AROMasterSubnet"
      aro_worker_subnet: "AROWorkerSubnet"
      aro_vnet_cidr: "100.100.0.0/16"
      aro_master_subnet_cidr: "100.100.10.0/24"
      aro_worker_subnet_cidr: "100.100.20.0/24"
      cluster_resource_group: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/$RESOURCE_GROUP-cluster"
      vent_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/Microsoft.Network/virtualNetworks/{{ aro_vnet }}"
      worker_subnet_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{resource_group}}/providers/Microsoft.Network/virtualNetworks/{{ aro_vnet }}/subnets/{{ aro_worker_subnet }}"
      master_subnet_id: "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{resource_group}}/providers/Microsoft.Network/virtualNetworks/{{ aro_vnet }}/subnets/{{ aro_master_subnet }}"

  tasks:

  - name: Creating Resource Group
    azure_rm_resourcegroup:
      name: "{{ resource_group }}"
      location: "{{  azure_dc }}"

  - name: Creating Virtual Network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group }}"
      name: "{{ aro_vnet }}"
      address_prefixes: "{{ aro_vnet_cidr }}"

# need to insert azure_rm_virtualnetwork_info to get resource ID of vnet

  - name: Creating 'Master' Subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ aro_master_subnet }}"
      address_prefix: "{{ aro_master_subnet_cidr }}"
      virtual_network: "{{ aro_vnet }}"

  - name: Creating 'Worker' Subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group }}"
      name: "{{ aro_worker_subnet }}"
      address_prefix: "{{ aro_worker_subnet_cidr }}"
      virtual_network: "{{ aro_vnet }}"

  - name: Disabling 'PrivateLinkServiceNetworkPolicies' in 'Master' Subnet
    azure_rm_resource:
        url: https://management.azure.com/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ aro_vnet }}/subnets/{{ aro_master_subnet }}?api-version=2020-03-01
        body: { "id": "/subscriptions/{{ lookup('env', 'AZURE_SUBSCRIPTION_ID') }}/resourceGroups/{{ resource_group }}/providers/Microsoft.Network/virtualNetworks/{{ aro_vnet }}/subnets/{{ aro_master_subnet }}",
                 "properties": {"addressPrefix": "{{ aro_master_subnet_cidr }}", 
                                "networkSecurityGroup": null,
                                "delegations": [],
                                "privateLinkServiceNetworkPolicies": "Disabled",
                                "privateEndpointNetworkPolicies": "Enabled"}, 
                 "name": "{{ aro_master_subnet }}"}

  - name: Getting Public IP address of Master HPC Infrastructure Node
    azure_rm_virtualnetwork_info:
      resource_group: "{{ resource_group }}"
      name: "{{ aro_vnet }}"
    register: output

  - debug:
      var: output

#  - name: Setting Public IP variable
#    set_fact:
#      mvn: "{{ output.virtualnetworks[0].subnets[1].id }}"

#  - name: Setting Public IP variable
#    set_fact:
#      wvn: "{{ output.virtualnetworks[0].subnets[0].id }}"


# Need to insert azure_rm_subnet_info to get resource IDs of subnets


#  - name: Create openshift cluster
#    azure_rm_openshiftmanagedcluster:
#      resource_group: "{{ resource_group }}"
#      name: "{{ cluster_name }}"
#      location: "{{ azure_dc }}"
#      cluster_profile:
#        cluster_resource_group_id: "{{ resource_group }}-cluster"
#        pull_secret: ""
##        domain: "{{ cluster_name }}"
#      service_principal_profile:
#        client_id: "{{ client_id }}"
#        client_secret: "{{ client_secret }}"
#      network_profile:
#        pod_cidr: "10.128.0.0/14"
#        service_cidr: "172.30.0.0/16"
#      worker_profiles:
#        name: "worker"
#        vm_size : "Standard_D4s_v3"
#        subnet_id : "{{ worker_subnet_id }}"
##        disk_size : 128
#        count : 3
#      master_profile:
#        vm_size : "Standard_D8s_v3"
#        subnet_id: "{{ master_subnet_id }}"
##     ingress_profiles:
##        visibility: "Public"
#      api_server_profile:
#        visibility: "Public"

  - name: Create openshift cluster
    azure_rm_openshiftmanagedcluster:
      resource_group: "{{ resource_group }}"
      name: "{{ cluster_name }}"
      location: "{{ azure_dc }}"
      service_principal_profile:
        client_id: "{{ client_id }}"
        client_secret: "{{ client_secret }}"
      worker_profiles:
#        name: "worker"
        - subnet_id : "{{ worker_subnet_id }}"
          count : 3
      master_profile:
        subnet_id: "{{ master_subnet_id }}"




